### ISSUE TITLE
Create a post (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#6]
> As a user,
So I can be a social butterfly,
I want to update others on my activities.

**Requirements**
- "Create post" input at the top of the dashboard post feed
- New posts should appear at the top of the lists of posts

--

**POST /post**
**Headers**
`Authorization: "Bearer <token>"`
```json
{
  "content": string
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/4

**Comment by Hoolio333** [comment]
Plan:

1) The team have noticed that there is already a 'Submit' button to create a post.

We can change the name from 'Submit' to 'Create Post"

2) Sorting is needed.

To do this we need to update Scheme.prisma (createdAt / updatedAt) - this will already be done server side.
The sorting will be done from top to bottom on the server side.
Therefore when a post is made it is in the correct order

**Comment by dogezen** [comment]
OK good plan - not knowing much about the existing code base, could you provide details of:

a) any React components that need implementing: do we have a Feed component? What about a Post component or a Dashboard component?
b) what happens when you click "Create Post"? how are you going to send data and what will you do to display errors OR once the post is successful?
