### ISSUE TITLE
Create delivery log (client)

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client#8]
> As a teacher,
So I can keep other teachers up to date on cohort progress,
I want to create delivery logs.

**Requirements**
- A form that only users with the `TEACHER` role can view / use
- Date field (defaults to the current date)
- Cohort ID field
- Ability to add / remove individual lines to the log as their own inputs

**POST /log**
**Headers**
`Authorization: "Bearer <token>"`
```json
{
  "date": ISO date string,
  "cohort_id": int,
  "lines": [
    {
      "content": string
    }
  ]
}
```

See the server response samples to handle responses: https://github.com/boolean-uk/team-dev-server/issues/6

**Comment by PBara7a** [comment]
![image](https://user-images.githubusercontent.com/72984740/175082556-deb6a86e-d135-4ccf-a69b-3e21eb174f29.png)

**Comment by PBara7a** [comment]
**User logged in data:**
-	When a user logs in, user info is to be stored in state (at App level). Each team can then access that info as needed and “prop it” into their components.
-	We can use this to conditionally render the delivery log only for teachers

**Form:**
-	Components: a date input, a number input for the cohort number, a Line component, a button to add more Line components to the form, a submit button.
-	The Line component has a text area and a remove button, to delete the component.

**How to access:**
-	The teacher can click a navigation link in the header and be directed to http://localhost:3000/log where the form and the delivery log are available. New route “/log” needed.
-	When the teacher submits the form, a status message will be updated. The message comes from the server side. 
-	If the submission is successful the new log is added to the delivery log rendered in the same page, no redirection.

**Comment by Auenc** [comment]
> Components: a number input for the cohort number

I think we could maybe do this in a slightly better way if we have the component rendered on a log specific to a cohort. For instance, if I wanted to add an entry for cohort 5, I the url could be something like `http://localhost:3000/cohort/5/log`

That way, we don't have to specify what cohort we're creating a log for via the form.

I don't think we're quite in the position to be able to do that yet, as we will need to be able to see a list of cohorts, be able to click on a cohort, and see a list of it's delivery logs. So for the time being, continue with the way you have suggested above, but with one caveat.

Instead of having a number input for the cohort, it would be a better UX experience to have a dropdown that contains a list of the existing cohorts. The user will then be able to select the cohort they wish to create a delivery log for. When the form is then submitted, you can look at the cohort the user has selected, and pass either the cohortID or the cohort number of the selected cohort to the API.

Does that make sense?

**Comment by dearshrewdwit** [comment]
There is a cohorts endpoint - `/cohort` https://github.com/boolean-uk/team-dev-server/blob/main/src/controllers/cohort.js

**Comment by dearshrewdwit** [comment]
Is this now unblocked @PBara7a ?

**Comment by PBara7a** [comment]
Yes, we created the route to get the available cohorts and finished the delivery log feature. @dearshrewdwit
